name: deploy preview website
"on":
  pull_request

env:
  NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
  CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
  SITE_URL: ${{ secrets.SITE_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "yarn"
      - run: npm config set @coldsurfers:registry https://npm.pkg.github.com/
      - run: npm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.GITHUB_TOKEN }}
      - run: yarn install --immutable
      - run: yarn build
      - run: npx vercel pull --yes --token ${{ secrets.VERCEL_TOKEN }}
      - run: npx vercel build
      - run: npx vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN }}
